description: Helm chart for the HMCTS CDM Document Management APO
apiVersion: v2
name: dm-store
home: https://github.com/hmcts/document-management-store-app
version: 2.1.23
maintainers:
  - name: HMCTS Evidence Management Team
    email: EvidenceManagement@HMCTS.NET
dependencies:
  - name: java
    version: 3.6.1
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
  - name: blobstorage
    version: 0.2.1
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
    condition: blobstorage.enabled
