api:
  version: 1.2.0

spring:
  application:
    name: dm-store
  data:
    rest:
      detection-strategy: annotated
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ssZ"
    serialization:
      indent_output: true
  http:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:90MB}
      max-request-size: ${MAX_FILE_SIZE:90MB}
  profiles:
    active: dev
  jpa:
    database-platform: uk.gov.hmcts.dm.dialect.CustomPostgresSqlDialect
    database: postgresql
    show-sql: ${SHOW_SQL:true}
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hiberante:
        dialect: uk.gov.hmcts.dm.dialect.CustomPostgresSqlDialect

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/evidence}
    username: ${SPRING_DATASOURCE_USERNAME:evidence}
    password: ${SPRING_DATASOURCE_PASSWORD:evidence}

    platform: postgresql
    time-between-eviction-runs-millis: ${STALE_CONN_EVICTION_FREQUENCY:60000}
    tomcat:
      max-active: ${MAX_ACTIVE_DB_CONNECTIONS:50} # Maximum number of active connections that can be allocated from this pool at the same time.
      max-idle: ${MAX_IDLE_DB_CONNECTIONS:25}
      max-wait: ${MAX_WAIT_DB_CONNECTIONS:10000} # Number of ms to wait before throwing an exception if no connection is available.
      test-on-borrow: ${TEST_ON_BORROW_DB_CONNECTION:true} # Validate the connection before borrowing it from the pool.
  batch:
    job:
      enabled: ${ENABLE_TTL:true}
      ttlCronExpression: ${TTL_CRON_EXPRESSION:"*/60 * * * * *"}
      auditUserName: ${TTL_JOB_AUDIT_USERNAME:"(admin)"}
      auditServiceName: ${TTL_JOB_AUDIT_SERVICE_NAME:"dm"}

liquibase:
 enabled: ${ENABLE_DB_MIGRATE:true}
 change-log: classpath:/db/changelog/db.changelog-master.xml

server:
  port: ${SERVER_PORT:4603}
  use-forward-headers: false

authorization:
  s2s-names-whitelist: ${S2S_NAMES_WHITELIST:sscs,divorce,ccd,em_gw,ccd_gw}

auth:
  idam:
    client:
      baseUrl: ${IDAM_USER_BASE_URI:http://localhost:4501}
  provider:
    service:
      client:
        baseUrl: ${IDAM_S2S_BASE_URI:http://localhost:4502}

security:
  headers:
    cache: false

logging:
  level:
    org.springframework.web: ${LOG_LEVEL_SPRING_WEB:INFO}
    uk.gov.hmcts.dm: ${LOG_LEVEL_DM:INFO}

azure:
  app_insights_key: ${APPINSIGHTS_INSTRUMENTATIONKEY:false}
  storage:
      connection-string: ${STORAGEACCOUNT_PRIMARY_CONNECTION_STRING:DefaultEndpointsProtocol=https;AccountName=yourAccountName;AccountKey=DmfyEajwVWcioSbjJWaR+EHYfP88CI2OScLlJGIQkmHTikiFwn1o2MHHysnyHgh586wKaP5fH9WrzWWjUZmv9uOa;EndpointSuffix=core.windows.net}
      blob-container-reference: ${STORAGE_CONTAINER_DOCUMENT_CONTAINER_NAME:dm-docstore-sandbox}

app-insights:
  dev-mode: off
  request-component: on
  telemetry-component: on

errors:
  globalIncludeStackTrace: ${SHOW_STACK_TRACE:true}

info:
  app:
    environment: ${PACKAGES_ENVIRONMENT:local}
    project: ${PACKAGES_PROJECT:evidence}
    name: ${PACKAGES_NAME:dm-store}
#    version: ${PACKAGES_VERSION:unknown}

health:
  status:
    order:
    - FATAL
    - DOWN
    - UNKNOWN
    - UP
  disk:
    threshold: ${HEALTH_DISK_THRESHOLD:262144000}

endpoints:
  health:
    sensitive: ${ENDPOINTS_HEALTH_SENSITIVE:false}
  info:
    sensitive: ${ENDPOINTS_INFO_SENSITIVE:false}

management:
  security:
    enabled: ${MANAGEMENT_SECURITY_ENABLED:false}
  diskspace:
    enabled: true
  db:
    enabled: true

dm:
  multipart:
    whitelist: ${DM_MULTIPART_WHITELIST:image/jpeg,application/pdf,image/tiff,image/png,image/bmp,text/plain,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.openxmlformats-officedocument.wordprocessingml.template,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.openxmlformats-officedocument.spreadsheetml.template,application/vnd.ms-powerpoint,application/vnd.openxmlformats-officedocument.presentationml.presentation,application/vnd.openxmlformats-officedocument.presentationml.template,application/vnd.openxmlformats-officedocument.presentationml.slideshow}
    whitelist-ext: ${DM_MULTIPART_WHITELIST_EXT:.jpg,.jpeg,.bmp,.tif,.tiff,.png,.pdf,.txt,.doc,.dot,.docx,.dotx,.xls,.xlt,.xla,.xlsx,.xltx,.xlsb,.ppt,.pot,.pps,.ppa,.pptx,.potx,.ppsx}

thumbnail:
    imageThumbnailCreator: ${SUPPORT_IMG_THUMBNAIL_MIME_TYPES:image/jpeg,image/png,image/gif,image/webp,image/bmp}
    pdfThumbnailCreator: ${SUPPORT_PDF_THUMBNAIL_MIME_TYPES:application/pdf}


toggle:
  includeidamhealth: ${ENABLE_IDAM_HEALTH_CHECK:false}
  metadatasearchendpoint: ${ENABLE_METADATA_SEARCH:true}
  documentandmetadatauploadendpoint: ${ENABLE_DOCUMENT_AND_METADATA_UPLOAD:true}
  folderendpoint: ${ENABLE_FOLDER_API:true}
  deleteenabled: ${ENABLE_DELETE:true}
  ttl: ${ENABLE_TTL:true}
  thumbnail: ${ENABLE_THUMBNAIL:true}



