base-urls.idam-user=${IDAM_API_URL:http://localhost:4501}
base-urls.idam-s2s=${S2S_URL:http://localhost:4502}
base-urls.s2s-token=${S2S_TOKEN:AAAAAAAAAAAAAAAA}
base-urls.dm-store=${TEST_URL:http://localhost:4603}
