version: '2.1'

services:
  document-management-node-demo:
    image: docker.artifactory.reform.hmcts.net/evidence/document-management-node-demo:latest
    environment:
    - NODE_ENV=development
    - PORT=8080
    - IDAM_CONTINUE_URL=http://localhost:3608
    - IDAM_API_URL=http://idam-api:8080
    - IDAM_LOGIN_URL=https://localhost:3501/login
    - DM_GW_BASE_URL=http://localhost:3603
    - DM_UPLOAD_URL=http://localhost:3603/documents
    - DM_OWNED_URL=http://localhost:3603/documents/owned
    - DM_SEARCH_URL=http://localhost:3603/documents/filter
    - DM_VIEWER_URL=http://localhost:3621
#      logging env vars
    - ROOT_APPENDER=JSON_CONSOLE
    - LOG_OUTPUT=single
    - JSON_CONSOLE_PRETTY_PRINT=false
    - REFORM_SERVICE_TYPE=node
    - REFORM_SERVICE_NAME=document-management-node-demo
    - REFORM_TEAM=evidence
    - REFORM_ENVIRONMENT=docker
#      healthcheck env vars
    - PACKAGES_ENVIRONMENT=docker
    - PACKAGES_PROJECT=evidence
    - PACKAGES_NAME=document-management-node-demo
    - PACKAGES_VERSION=unkown
    links:
     - document-management-store-api-gateway-web
     - idam-api
     - service-auth-provider-api
    depends_on:
     - document-management-store-api-gateway-web
     - idam-api
     - service-auth-provider-api

#  document-management-store:
#    build:
#      context: ..
#    image: docker.artifactory.reform.hmcts.net/evidence/document-management-store:latest
#    command: --wait-for-database 30
#    environment:
#      - SERVER_PORT=8080
#      - IDAM_SUPERUSER_EMAIL
#      - IDAM_SECRET_KEY=AAAAAAAAAAAAAAAA
#      - GOV_NOTIFY_API_KEY
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://document-management-store-database:5432/evidence
#      - SPRING_DATASOURCE_USERNAME=evidence
#      - SPRING_DATASOURCE_PASSWORD=evidence
#      - SPRING_PROFILES_ACTIVE=dev
#      - IDAM_TESTING_SUPPORT_ENABLED=true
#      - LOGGING_LEVEL_UK_GOV_HMCTS_IDAM=DEBUG
#      - IDAM_USER_BASE_URI=http://idam-api:8080
#      - IDAM_S2S_BASE_URI=http://service-auth-provider-api:8080
#      - http_proxy=
#      - https_proxy=
#      - no_proxy=
##      logging env vars
#      - ROOT_APPENDER=JSON_CONSOLE
#      - JSON_CONSOLE_PRETTY_PRINT=false
#      - REFORM_SERVICE_TYPE=java
#      - REFORM_SERVICE_NAME=document-management-store-app
#      - REFORM_TEAM=evidence
#      - REFORM_ENVIRONMENT=docker
##      healthcheck env vars
#      - PACKAGES_ENVIRONMENT=docker
#      - PACKAGES_PROJECT=evidence
#      - PACKAGES_NAME=document-management-store-app
#      - PACKAGES_VERSION=unkown
##      debug mode
#      - JAVA_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
#    links:
#     - document-management-store-database
#     - idam-api
#     - service-auth-provider-api
#    depends_on:
#     - document-management-store-database
#     - idam-api
#     - service-auth-provider-api

  document-management-store-database:
    build:
        context: ../database/.
    image: docker.artifactory.reform.hmcts.net/evidence/document-management-store-database:latest
