base-urls.dm-api-gw-web=${DM_GW_BASE_URI:http://localhost:3603}
base-urls.idam-user=${IDAM_USER_BASE_URI:http://localhost:4501}
base-urls.idam-s2s=${IDAM_S2S_BASE_URI:http://localhost:4502}
base-urls.dm-store-app=${TEST_URL:http://localhost:4603}

login.username=${TEST_USERNAME:test@test.com}
login.password=${TEST_PASSWORD:password}
login.token=${TEST_TOKEN:token}

toggle.metadatasearchendpoint=${ENABLE_METADATA_SEARCH:true}
toggle.documentandmetadatauploadendpoint=${ENABLE_DOCUMENT_AND_METADATA_UPLOAD:true}
toggle.folderendpoint=${ENABLE_FOLDER_API:true}
toggle.includeidamhealth=${ENABLE_IDAM_HEALTH_CHECK:false}
toggle.deleteenabled=${ENABLE_DELETE:true}
toggle.ttl=${ENABLE_TTL:true}
toggle.thumbnail=${ENABLE_THUMBNAIL:true}
