---
version: '2.1'

services:

  em-viewer-web:
    ports:
     - 3621:8080

  em-api-gateway-web:
    ports:
     - 3623:8080

  em-annotation-app:
    ports:
      - 4621:8080

#  em-annotation-app-database:
#    ports:
#      - 5432:5432

  em-redaction-app:
    ports:
      - 4623:8080

#  em-redaction-app-database:
#    ports:
#      - 5432:5432

